version: "2.23.0"
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=flights
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user123
    ports:
      - 33060:3306
    volumes:
      - data_sql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 5

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - data_redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 50s
      retries: 5

  rabbitmq:
    container_name: rabbitmq
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "node_health_check"]
      interval: 30s
      timeout: 5s
      retries: 3
    volumes:
      - data_rabbitmq:/var/lib/rabbitmq

  flight-microservice:
    build: ./api
    container_name: flight
    image: maven:3-openjdk-17
    volumes:
      - ./api:/api
    ports:
      - "8082:8080"
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url":"jdbc:mysql://mysql:3306/flights",
        "spring.datasource.username":"user",
        "spring.datasource.password":"user123",
        "spring.redis.host":"redis",
        "spring.redis.port":"6379",
        "spring.rabbitmq.host":"rabbitmq",
        "spring.rabbitmq.port":"5672",
        "spring.rabbitmq.username":"admin",
        "spring.rabbitmq.password":"admin"
        }'
    working_dir: /flight-microservice/api
    command: sh -c "./mvnw spring-boot:run"

volumes:
  data_sql:
    driver: local
  data_rabbitmq:
    driver: local
  data_redis:
    driver: local
